### ISSUE TITLE
Unir todo en un unico test

### ISSUE THREAD

**Issue by FabrizioOtranto** [mhooes/pushingit#1]
Buenas!!

Esta todo muy bien pero todo deberia ser unido en un test que registre, agregue la tarea y la complete (todo en un unico it)

Luego mas adelante vamos a aprender a usar hooks para organizar mejor todo

Saludos!

https://github.com/mhooes/pushingit/blob/a454e26eb8176ebf84130e39512a01c8e74d14d4/cypress/e2e/desafio1.cy.js#L5

**Comment by mhooes** [comment]
Genial, ya lo arregle.
https://github.com/mhooes/pushingit/blob/aa0f9478f153e86be4a9b63a5532bb121dc5ca6d/cypress/e2e/desafio1.cy.js#L1-L22
